let news = [
  {
    id: 0,
    title:
      "Мирзиёев рассказал, зачем было построено Сардобинское водохранилище",
    img: "../images/hero1.png",
    time: "05:28",
    date: "2020-05-06",
    categories: ["uzbekistan", "siyosat"],
  },
  {
    id: 1,
    title: "Карантин в Узбекистане продлен до 1 июня",
    img: "../images/hero2.png",
    time: "05:28",
    date: "2020-05-06",
    categories: ["uzbekistan"],
  },
  {
    id: 2,
    title: "Обмелевшая Сардоба: стихия или человеческий фактор?",
    img: "../images/hero3.png",
    time: "05:28",
    date: "2020-05-06",
    categories: ["uzbekistan", "siyosat", "sport"],
  },
  {
    id: 3,
    title: "Следствие проверяет четыре версии прорыва Сардобинской плотины",
    img: "../images/hero4.png",
    time: "05:28",
    date: "2020-05-06",
    categories: ["uzbekistan", "jahon"],
  },
  {
    id: 4,
    title: "Выявлено еще 7 случаев коронавируса",
    img: "../images/hero5.png",
    time: "05:28",
    date: "2020-05-06",
    categories: ["jahon", "siyosat"],
  },
  {
    id: 5,
    title: "Итоги второго месяца карантина",
    img: "../images/hero6.png",
    time: "05:28",
    date: "2020-05-06",
    categories: ["uzbekistan", "siyosat"],
  },
  {
    id: 6,
    title: "Турецкого комментатора сняли с эфира в перерыве матча ЧМ-2022",
    img: "https://storage.kun.uz/source/thumbnails/_medium/9/VC32U3xI75KYRjOgZ2nctZkf7P78Dg0P_medium.jpeg",
    time: "05:28",
    date: "2020-05-06",
    categories: ["sport"],
  },
  {
    id: 7,
    title: "Криштиану Роналду побил мировой рекорд по забитым мячам за сборную",
    img: "https://storage.kun.uz/source/thumbnails/_medium/7/XARTkzxetArsxELT0CO1YspmWgnRPzD9_medium.jpg",
    time: "05:28",
    date: "2020-05-06",
    categories: ["jahon", "sport"],
  },
  {
    id: 8,
    title: "Шавкат Мирзиёев посетит Кыргызстан",
    img: "https://storage.kun.uz/source/thumbnails/_medium/9/dWhM4_3PdHMmXGxRyfaQGY74vqymEa3c_medium.jpg",
    time: "05:28",
    date: "2020-05-06",
    categories: ["uzbekistan", "jahon", "siyosat"],
  },
  {
    id: 9,
    title:
      "Первая леди Украины рассказала о жизни во время войны и вере в победу",
    img: "https://storage.kun.uz/source/thumbnails/_medium/9/EJkF4XbhmhluxWQVsiu5ddvSY9csdS8c_medium.jpg",
    time: "05:28",
    date: "2022-05-06",
    categories: ["jahon"],
  },
  {
    id: 10,
    title:
      "Сборная Узбекистана по шахматам стала обладательницей серебряных медалей командного чемпионате мира ФИДЕ",
    img: "https://storage.kun.uz/source/thumbnails/_medium/9/gWwfBrsTJP3wqpeyUpx-iWP1_XskphgX_medium.jpg",
    time: "05:28",
    date: "2022-05-06",
    categories: ["sport", "jahon"],
  },
  {
    id: 11,
    title: "Депутат из Намангана, который критиковал узбекистанцев, уволился",
    img: "https://storage.kun.uz/source/thumbnails/_medium/9/cd4EqmjbTfwQ_k-WR0ZIWAzKsrewrWV__medium.jpg",
    time: "05:28",
    date: "2022-05-06",
    categories: ["siyosat", "jahon"],
  },
];
